// const MULTIPLIER = 10;
// export const pointsConfig = {
//     COMPLETED: 3 / MULTIPLIER,
//     ATTEMPTED: 1 / MULTIPLIER,
//     UNTOUCHED: -3 / MULTIPLIER,
//     STREAK: 6 / MULTIPLIER,
// };

const MULTIPLIER = 10;
export const pointsConfig = {
    COMPLETED_MAJOR: 4 / MULTIPLIER,
    COMPLETED_MINOR: 2 / MULTIPLIER,
    ATTEMPTED: 1 / MULTIPLIER,
    UNTOUCHED_MAJOR: -4 / MULTIPLIER,
    UNTOUCHED_MINOR: -2 / MULTIPLIER,
    STREAK: 2,
};

